version: '2'
volumes:
  db:
  staging:
  static:
  store:
services:
  db:
    image: postgres
    restart: always
    environment:
      - DB_NAME=mytardis-development
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
    volumes:
      - db:/var/lib/postgresql
  app:
    build: .
    restart: always
    volumes:
      - staging:/srv/mytardis/var/staging/
      - static:/srv/mytardis/static/
      - store:/srv/mytardis/var/store/
    ports:
      - "8000:8000"
    command: --forwarded-allow-ips="*"
    links:
      - db
      - rabbit
    environment:
      - MYTARDIS_ALLOWED_HOSTS='*'
      - MYTARDIS_STORAGE_BASE_DIR=/srv/mytardis/var/store
      - MYTARDIS_STATIC=/srv/mytardis/static/
      - MYTARDIS_TIME_ZONE=Australia/Perth
      - MYTARDIS_ENABLE_FILTER_BIOFORMATS='True'
      - GUNICORN_LOG_LEVEL=debug
      - GUNICORN_WORKER_CLASS=gevent
    env_file:
      - env.mytardis_secret_key
      - env.mytardis_email
      - env.mytardis_ldap_1
  static:
    image: nginx
    restart: always
    volumes:
      - static:/srv/static/:ro
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=mytardis-static.science.uwa.edu.au
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  rabbit:
    image: rabbitmq:3-management
    hostname: django-rabbit-001
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret cookie here'
    ports:
      - '15672:15672'
  celery:
    build:
      context: .
      dockerfile: Dockerfile-mytardis_celery
    volumes:
      - staging:/srv/mytardis/var/staging/
      - static:/srv/mytardis/static/
      - store:/srv/mytardis/var/store/
    links:
      - db
      - rabbit
    environment:
      - MYTARDIS_ALLOWED_HOSTS='*'
      - MYTARDIS_STORAGE_BASE_DIR=/srv/mytardis/var/store
      - MYTARDIS_STATIC=/srv/mytardis/static/
      - MYTARDIS_TIME_ZONE=Australia/Perth
      - MYTARDIS_ENABLE_FILTER_BIOFORMATS='True'
    env_file:
      - env.mytardis_secret_key
      - env.mytardis_email
  ssh:
    build:
      context: .
      dockerfile: Dockerfile-mytardis_ssh
    volumes:
      - staging:/srv/mytardis/var/staging/
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile-mytardis_haproxy
    command: /bin/bash -c "envsubst < /usr/local/etc/haproxy/haproxy.cfg.template > /usr/local/etc/haproxy/haproxy.cfg && haproxy -f /usr/local/etc/haproxy/haproxy.cfg"
    environment:
      - MYTARDIS_MAXCONN=2048
    links:
      - app
      - static
      - ssh
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg.template:/usr/local/etc/haproxy/haproxy.cfg.template
      - ./pki/localhost.pem:/localhost.pem
