version: "2"
services:
  db:
    image: postgres
  app:
    build: ./app
    volumes:
      - ./vol/tardis/settings.py:/srv/mytardis/tardis/settings.py
      - ./vol/static/:/srv/mytardis/static/
    ports:
      - "8000:8000"
    command: --forwarded-allow-ips="*" --log-level=debug
    depends_on:
      - db
  static:
    image: nginx
    volumes:
      - ./vol/static/:/srv/:ro
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=mytardis-static.science.uwa.edu.au
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
