version: "2"
volumes:
  db:
  staging:
  static:
  store:
services:
  db:
    image: postgres
    restart: always
    environment:
      - DB_NAME=mytardis-development
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=repluserpass
    volumes:
      - db:/var/lib/postgresql
  app:
    build: .
    restart: always
    volumes:
      - staging:/srv/mytardis/var/staging/
      - static:/srv/mytardis/static/
      - store:/srv/mytardis/var/store/
    ports:
      - "8000:8000"
    command: --forwarded-allow-ips="*" --log-level=debug
    links:
      - db
      - rabbit
    environment:
      - MYTARDIS_ALLOWED_HOSTS='*'
      - MYTARDIS_STORAGE_BASE_DIR=/srv/mytardis/var/store
      - MYTARDIS_STATIC=/srv/mytardis/static/
      - MYTARDIS_TIME_ZONE=Australia/Perth
      - MYTARDIS_EMAIL_PORT=25
      - MYTARDIS_EMAIL_HOST=<enter_smtp_smarthost>
  static:
    image: nginx
    restart: always
    volumes:
      - static:/srv/:ro
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=mytardis-static.science.uwa.edu.au
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  rabbit:
    image: rabbitmq:3-management
    hostname: django-rabbit-001
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret cookie here'
    ports:
      - '8080:15672'
  celery:
    image: celery
    links:
      - rabbit
    volumes:
      - ./src/mytardis/tardis/tardis_portal:/home/user
